PL_MVC/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno

        [HttpGet]
        public ActionResult GetAll()
        {
            ServiceAlumno.AlumnoClient context = new ServiceAlumno.AlumnoClient();

            var result = context.GetAll();
            ML.Alumno alumno = new ML.Alumno();
            alumno.Alumnos = new List<object>();

            if (result.Correct)
            {
                foreach(var obj in result.Objects)
                {
                    alumno.Alumnos.Add(obj);
                }
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al hacer la consulta";
            }

            return View(alumno);
        }

        [HttpGet]
        public ActionResult Form(int? IdAlumno)
        {
            ML.Alumno alumno = new ML.Alumno();

            if(IdAlumno == null)
            {
                return View(alumno);
            }
            else
            {
                ServiceAlumno.AlumnoClient context = new ServiceAlumno.AlumnoClient();

                var result = context.GetById(IdAlumno.Value);
                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al obtener al alumno";
                }
                return View(alumno);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            if(alumno.IdAlumno == 0)
            {
                ServiceAlumno.AlumnoClient context = new ServiceAlumno.AlumnoClient();

                var result = context.Add(alumno);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = result.Message;
                }

            }
            else
            {
                ServiceAlumno.AlumnoClient context = new ServiceAlumno.AlumnoClient();

                var result = context.Update(alumno);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = result.Message;
                }
                
            }

            return PartialView("Modal");
        }

        public ActionResult Delete(int IdAlumno)
        {
            if(IdAlumno > 0)
            {
                ServiceAlumno.AlumnoClient context = new ServiceAlumno.AlumnoClient();

                var result = context.Delete(IdAlumno);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = result.Message;
                }
                
            }

            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Agregar Alumno</h2>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multiplaform/form-data" }))
            {
                <div class="row">
                    <div class="col-3 hidden">
                        <div class="form-group">
                            <div class="col-md-1">
                                @Html.LabelFor(model => model.IdAlumno, new { @class = "hidden" })
                                @Html.TextBoxFor(model => model.IdAlumno, new { @class = "hidden form-control" })
                                @Html.ValidationMessageFor(model => Model.IdAlumno)
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.Nombre)
                                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @onkeypress = "return SoloLetras(event, 'lblNombre')" })
                                @Html.ValidationMessageFor(model => model.Nombre)
                                @Html.Label("", null, new { @id = "lblNombre", @style = "display: block;" })
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.ApellidoPaterno)
                                @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @onkeypress="return SoloLetras(event, 'lblApellidoPaterno')" })
                                @Html.ValidationMessageFor(model => model.ApellidoPaterno)
                                @Html.Label("", null, new {@id = "lblApellidoPaterno", @style="display: block;" })
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.ApellidoMaterno)
                                @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class ="form-control", @onkeypress="return SoloLetras(event, 'lblApellidoMaterno')"})
                                @Html.ValidationMessageFor(model => model.ApellidoMaterno)
                                @Html.Label("", null, new {@id = "lblApellidoMaterno", @style="display: block;" })
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class=" col-4">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
                    </div>
                </div>
            }


        </div>

    </div>
</div>


@section Scripts
{

    <script type="text/javascript">

        function SoloLetras(e, controlId) {
            var caracter = e.key;
            if (!/^[a-zA-Z\u00C0-\u00FF ]*$/g.test(caracter)) {
                $('#' + controlId).text("Solo se aceptan letras");
                $('#' + controlId).css({ "color": "red" });
                return false;
            }
            else {
                $('#' + controlId).text("");
                return true;
            }
        }


    </script>
 }

PL_MVC/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Alumnos</h2>
        </div>
    </div>

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success" })
        </div>

    </div>

    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id Alumno</th>
                    <th>Nombre</th>
                    <th>Apellido Paterno</th>
                    <th>Apellido Materno</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Alumno alumno in Model.Alumnos)
                {
                    <tr>
                        <td>@alumno.IdAlumno</td>
                        <td>@alumno.Nombre</td>
                        <td>@alumno.ApellidoPaterno</td>
                        <td>@alumno.ApellidoMaterno</td>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Alumno", new {IdAlumno = alumno.IdAlumno})"></a></td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Alumno", new {IdAlumno = alumno.IdAlumno})" onclick=" return confirm('Estas seguro que quieres eliminar el resgitro=');" ></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

</div>

PL_MVC/Views/Alumno/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>