PL_MVC/Controllers/AlumnoMateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AlumnoMateriaController : Controller
    {
        // GET: AlumnoMateria
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            ML.Result result = BL.Alumno.AlumnoGetAll();
            if (result.Correct)
            {
                alumno.Alumnos = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error en mostrar los alumnos";
            }

            return View(alumno);
        }

        [HttpGet]
        public ActionResult MateriasAsignadas(int IdAlumno)
        {
            decimal total = 0;
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            ML.Result result = BL.AlumnoMateria.GetAlumnoMateriaByIdAlumno(IdAlumno);

            if (result.Correct)
            {
                alumnoMateria.AlumnoMaterias = result.Objects;
            }

            alumnoMateria.Alumno = new ML.Alumno();

            ML.Result resultAlumno = BL.Alumno.GetById(IdAlumno);
            if (resultAlumno.Correct)
            {
                alumnoMateria.Alumno = (ML.Alumno)resultAlumno.Object;
            }

            if(alumnoMateria.AlumnoMaterias.Count > 0)
            {
                foreach(ML.AlumnoMateria materiacosto in alumnoMateria.AlumnoMaterias)
                {
                    total = total + materiacosto.Materia.Costo;
                }
            }

            ViewBag.Correct = true;
            ViewBag.Total = total;

            return View(alumnoMateria);

        }

        [HttpGet]
        public ActionResult AsignarMateria(int IdAlumno)
        {
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();

            ML.Result result = BL.AlumnoMateria.GetSinAsignarByIdAlumno(IdAlumno);
            if (result.Correct)
            {
                alumnoMateria.AlumnoMaterias = result.Objects;
            }
            

            ML.Result resultAlumno = BL.Alumno.GetById(IdAlumno);

            if (resultAlumno.Correct)
            {
                alumnoMateria.Alumno = (ML.Alumno)resultAlumno.Object;
            }

            

            return View(alumnoMateria);
        }


        [HttpPost]
        public ActionResult Asignar(ML.AlumnoMateria alumnoMateria)
        {
            ML.Result result = new ML.Result(); 
            if(alumnoMateria.AlumnoMaterias != null)
            {
                foreach(string IdMataria in alumnoMateria.AlumnoMaterias)
                {
                    ML.AlumnoMateria alumnoMateriaItem = new ML.AlumnoMateria();

                    alumnoMateriaItem.Alumno = new ML.Alumno();

                    alumnoMateriaItem.Alumno.IdAlumno = alumnoMateria.Alumno.IdAlumno;

                    alumnoMateriaItem.Materia = new ML.Materia();

                    alumnoMateriaItem.Materia.IdMateria = int.Parse(IdMataria);

                    ML.Result resulAdd = BL.AlumnoMateria.Add(alumnoMateriaItem);
                }

                result.Correct = true;
                ViewBag.Message = "Se ha asignado materia(s)";
                ViewBag.MateriasAsigandas = true;
                ViewBag.IdAlumno = alumnoMateria.Alumno.IdAlumno;
            }
            else
            {
                result.Correct = false;
                ViewBag.Message = "No se asigno la materia(s)";
                ViewBag.MateriasAsigandas = false;
                ViewBag.IdAlumno = alumnoMateria.Alumno.IdAlumno;
            }

            return PartialView("Modal");
        }

        [HttpGet]
        public ActionResult Eliminar(int IdAlumno, int IdMateria)
        {
            ML.Result result = BL.AlumnoMateria.EliminarMateria(IdAlumno, IdMateria);
            if (result.Correct)
            {
                result.Correct = true;
                ViewBag.Message = result.Message;
                ViewBag.MateriasAztualizadas = true;
                ViewBag.IdAlumno = IdAlumno;
            }
            else
            {
                result.Correct = false;
                ViewBag.Message = result.Message;
                ViewBag.MateriasAztualizadas = false;
                ViewBag._IdAlumno = IdAlumno;
            }

            return PartialView("Modal");
        }
    
    }
}

PL_MVC/Views/AlumnoMateria/AsignarMateria.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "AsignarMateria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Asignar Materia</h2>

<div class="container">

    <div class="row">
        <div class="col-lg-3 hidden">
            <div class="form-group">
                <div class="col-md-1">
                    @Html.LabelFor(model => model.Alumno.IdAlumno, new { @class = "hidden" })
                    @Html.TextBoxFor(model => model.Alumno.IdAlumno, new { @class = "hidden form-control" })
                    @Html.ValidationMessageFor(model => model.Alumno.IdAlumno)
                </div>
            </div>
        </div>

        <div class="col-lg-3 text-center">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Alumno</h3>
                </div>
                <div class="panel-body">
                    @Model.Alumno.Nombre @Model.Alumno.ApellidoPaterno @Model.Alumno.ApellidoMaterno
                </div>
            </div>
        </div>
    </div>


    <div class="row">

        @if (Model.AlumnoMaterias.Count > 0)
        {
            <div class="row">

                @using (Html.BeginForm("Asignar", "AlumnoMateria", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Id Materia</th>
                                <th class="text-center">Elegir</th>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Costo</th>
                            </tr>
                        </thead>
                        <tbody>




                            @foreach (ML.Materia alumnoMateria in Model.AlumnoMaterias)
                            {
                                <tr>
                                    <td class="text-center">@alumnoMateria.IdMateria</td>

                                    <td class="text-center">
                                        <input type="checkbox" value="@alumnoMateria.IdMateria" name="AlumnoMaterias" />
                                    </td>
                                    <td class="text-center">
                                        @alumnoMateria.Nombre
                                    </td>
                                    <td class="text-center">@alumnoMateria.Costo</td>
                                </tr>
                            }

                            @*<div class="col-1">
                                <input type="submit" value="Guardar" class="btn btn-info" />
                            </div>
                            </form*@
                        </tbody>


                    </table>
                    @Html.HiddenFor(model => model.Alumno.IdAlumno)

                    <div class="text-center form-gorup" style="margin: 0 auto;">
                        <div class="col-md-12">

                            <a class="btn btn-danger" style="margin-right: 40px;" href="@Url.Action("MateriasAsignadas","AlumnoMateria", new { IdAlumno =  @Model.Alumno.IdAlumno})">Regresar</a>

                            <input type="submit" value="Actualizar" class="btn btn-success" />

                        </div>
                    </div>
                }
            </div>

        }
        else
        {
            <div class="">
                <div class="alert alert-success" role="alert">El Alumno ya tiene todas las materias</div>
            </div>
            <div class="text-center form-gorup" style="margin: 0 auto;">
                <div class="col-md-12">

                    <a class="btn btn-danger" style="margin-right: 40px;" href="@Url.Action("MateriasAsignadas","AlumnoMateria", new { IdAlumno =  @Model.Alumno.IdAlumno})">Regresar</a>

                </div>
            </div>
        }

        @*<div class="col-lg-3" style="margin-top: ">
            <div class="text-center" style="float:left;">
                <a class="btn btn-danger" href="@Url.Action("MateriasAsignadas","AlumnoMateria", new { IdAlumno =  @Model.Alumno.IdAlumno})">Regresar</a>
            </div>

        </div>*@


    </div>

</div>

PL_MVC/Views/AlumnoMateria/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Alumnos</h2>
        </div>
    </div>



    <div class="row">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="hidden">Id Alumno</th>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Editar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Alumno alumno in Model.Alumnos)
                {
                    <tr>
                        <td class="hidden">@alumno.IdAlumno</td>
                        <td class="text-center">@alumno.Nombre @alumno.ApellidoPaterno @alumno.ApellidoMaterno</td>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("MateriasAsignadas", "AlumnoMateria", new {IdAlumno = alumno.IdAlumno})"></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

</div>

PL_MVC/Views/AlumnoMateria/MateriasAsignadas.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "MateriasAsignadas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Materias Asignadas</h2>
<div class="container">
    <div class="row">
        <div class="col-lg-3 hidden">
            <div class="form-group">
                <div class="col-md-1">
                    @Html.LabelFor(model => model.Alumno.IdAlumno, new { @class = "hidden" })
                    @Html.TextBoxFor(model => model.Alumno.IdAlumno, new { @class = "hidden form-control" })
                    @Html.ValidationMessageFor(model => model.Alumno.IdAlumno)
                </div>
            </div>
        </div>

        <div class="col-lg-3 text-center">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Alumno</h3>
                </div>
                <div class="panel-body">
                    @Model.Alumno.Nombre @Model.Alumno.ApellidoPaterno @Model.Alumno.ApellidoMaterno
                </div>
            </div>



            @*<div class="form-group">
                <div class="">
                    <input type="text" class="form-control" readonly value="@Model.Alumno.IdAlumno  @Model.Alumno.Nombre @Model.Alumno.ApellidoPaterno @Model.Alumno.ApellidoMaterno" >
                    @Model.Alumno.IdAlumno  @Model.Alumno.Nombre @Model.Alumno.ApellidoPaterno @Model.Alumno.ApellidoMaterno
                </div>
            </div>*@
        </div>
    </div>

    <div class="row" style="margin-bottom: 10px;">
        <div class="" style="float:right">
            <a class="btn btn-success glyphicon glyphicon-plus" href="@Url.Action("AsignarMateria","AlumnoMateria", new { IdAlumno =  @Model.Alumno.IdAlumno})"></a>
        </div>

    </div>

    <div class="row">

        @if (Model.AlumnoMaterias.Count == 0)
        {
        <div class="">
            <div class="alert alert-danger" role="alert">El Alumno elegido no tiene materias Asignadas</div>
        </div>
            
        }
        else
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">Id Materia</th>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Costo</th>


                        <th class="text-center">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.AlumnoMateria alumnoMateria in Model.AlumnoMaterias)
                    {
                        <tr>
                            <td class="text-center">@alumnoMateria.Materia.IdMateria</td>
                            <td class="text-center">@alumnoMateria.Materia.Nombre</td>
                            <td class="text-center">@alumnoMateria.Materia.Costo</td>


                            <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Eliminar", "AlumnoMateria", new {IdAlumno = Model.Alumno.IdAlumno, IdMateria = alumnoMateria.Materia.IdMateria})" onclick=" return confirm('Estas seguro que quieres eliminar el resgitro?');"></a></td>
                        </tr>
                    }

                </tbody>
            </table>

            <div class="row" style="margin-top: 17px;">

                <div class="text-center form-gorup" style="float:left">
                    <div class="col-md-3">

                        <a class="btn btn-danger" style="margin-right: 40px;" href="@Url.Action("GetAll","AlumnoMateria")">Regresar</a>

                    </div>
                </div>

                <div class="col-lg-3 text-center" style="float: right;">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h3 class="panel-title">Total</h3>
                        </div>
                        <div class="panel-body">
                            $@ViewBag.Total
                        </div>
                    </div>
                </div>
            </div>

            @*<div class="row">
                <div class="text-center form-gorup" style="float">
                    <div class="col-md-3">

                        <a class="btn btn-danger" style="margin-right: 40px;" href="@Url.Action("GetAll","AlumnoMateria")">Regresar</a>

                    </div>
                </div>
            </div>*@

           

        }




    </div>

</div>

PL_MVC/Views/AlumnoMateria/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @if (ViewBag.MateriasAztualizadas == true)
                {
                    <a class="btn btn-info" href="@Url.Action("MateriasAsignadas", "AlumnoMateria",new{ IdAlumno =  ViewBag.IdAlumno })">Aceptar</a>
                    
                }
            else
            {
                    <a class="btn btn-info" href="@Url.Action("GetAll", "AlumnoMateria")">Regresar</a>
            }

                
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>