PL_MVC/Controllers/MateriaController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class MateriaController : Controller
    {
        // GET: Materia
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Materia materia = new ML.Materia();

            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApiUrl"]);

                    var responseTask = client.GetAsync("Materia/GetAll");

                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        foreach(var resultItem in readTask.Result.Objects)
                        {
                            ML.Materia resultItemList  = JsonConvert.DeserializeObject<ML.Materia>(resultItem.ToString());
                            result.Objects.Add(resultItemList);
                        }

                        result.Correct = true;
                    }

                }
            
            }
            catch(Exception ex)
            {
                result.Correct = false;
                result.Message = ex.Message;
            }

            if (result.Correct)
            {
                materia.Materias = result.Objects;
                return View(materia);
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta ";
                return PartialView("Modal");
            }
            
        }

        [HttpGet]
        public ActionResult Form(int? IdMateria)
        {
            ML.Materia materia = new ML.Materia();

            if(IdMateria == null)
            {
                return View(materia);
            }
            else
            {
                ML.Result result = new ML.Result();
                try
                {

                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApiUrl"]);

                        var responseTask = client.GetAsync("Materia/GetById/" + IdMateria.Value);

                        responseTask.Wait();

                        var resultServicio = responseTask.Result;

                        if (resultServicio.IsSuccessStatusCode)
                        {
                            var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();

                            readTask.Wait();

                            ML.Materia materiaItem = new ML.Materia();
                            materiaItem = JsonConvert.DeserializeObject<ML.Materia>(readTask.Result.Object.ToString());
                            result.Object = materiaItem;
                            result.Correct = true;
                        }
                        else
                        {
                            result.Correct = false;
                        }
                    }
                }
                catch (Exception ex)
                {
                    result.Correct = false;
                    result.Message = ex.Message;
                }

                if (result.Correct)
                {
                    materia = (ML.Materia)result.Object;

                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar la materia seleccionada";
                }
                return View(materia);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Materia materia)
        {
            if(materia.IdMateria == 0)
            {
                ML.Result result = new ML.Result();
                try
                {
                    using(var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApiUrl"]);

                        var postTask = client.PostAsJsonAsync<ML.Materia>("Materia/Add", materia);

                        postTask.Wait();

                        var resultServicio = postTask.Result;

                        if (resultServicio.IsSuccessStatusCode)
                        {
                            result.Correct = true;
                        }
                        else
                        {
                            result.Correct = false;
                            result.Message = "Ocurrio un error al agregar la Materia";
                        }
                    }
                }
                catch(Exception ex)
                {
                    result.Correct = false;
                    result.Message = ex.Message;
                }

                if (result.Correct)
                {
                    ViewBag.Message ="Se ha agregado la Materia";
                }
                else
                {
                    ViewBag.Messsage = "Error:  " + result.Message;
                }
            }
            else
            {
                ML.Result result = new ML.Result();

                try
                {
                    using(var cliente = new HttpClient())
                    {
                        cliente.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApiUrl"]);

                        var postask = cliente.PutAsJsonAsync<ML.Materia>("Materia/Update/" + materia.IdMateria, materia);

                        postask.Wait();

                        var resultServicio = postask.Result;

                        if (resultServicio.IsSuccessStatusCode)
                        {
                            result.Correct = true;
                        }
                        else
                        {
                            result.Correct = false;
                            result.Message = "Ocurrio un error al actualizar la materia";
                        }
                    }

                }
                catch (Exception ex)
                {
                    result.Correct = false;
                    result.Message = ex.Message;
                }
                if (result.Correct)
                {
                    ViewBag.Message = "Se ha actualiado la materia";
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            return PartialView("Modal");
        }

        public ActionResult Delete(int IdMateria)
        {
            ML.Result result = new ML.Result();

            if(IdMateria > 0)
            {
                try
                {
                    using(var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApiUrl"]);

                        var responseTask = client.DeleteAsync("Materia/Delete/" + IdMateria);

                        responseTask.Wait();

                        var resultServicio = responseTask.Result;

                        if (resultServicio.IsSuccessStatusCode)
                        {
                            result.Correct = true;
                        }
                    }
                }
                catch(Exception ex)
                {
                    result.Correct = false;
                    result.Message = ex.Message;
                }
                if (result.Correct)
                {
                    ViewBag.Message = "Se ha elimnado el Usuario";
                }
            }

            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Materia/Form.cshtml
@model ML.Materia
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Materia</h2>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Materia", FormMethod.Post, new { enctype = "multiplaform/form-data" }))
            {
                <div class="row">
                    <div class="col-3 hidden">
                        <div class="form-group">
                            <div class="col-md-1">
                                @Html.LabelFor(model => model.IdMateria, new { @class = "hidden" })
                                @Html.TextBoxFor(model => model.IdMateria, new { @class = "hidden form-control" })
                                @Html.ValidationMessageFor(model => Model.IdMateria)
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.Nombre)
                                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @onkeypress = "return SoloLetras(event, 'lblNombre')" })
                                @Html.ValidationMessageFor(model => model.Nombre)
                                @Html.Label("", null, new { @id = "lblNombre", @style = "display: block;" })
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.Costo)
                                @Html.TextBoxFor(model => model.Costo, new { @class = "form-control"  })
                                @Html.ValidationMessageFor(model => model.Costo)
                                @Html.Label("", null, new { @id = "lblApellidoPaterno", @style = "display: block;" })
                            </div>
                        </div>
                    </div>

               

                </div>

                <div class="row">
                    <div class=" col-4">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
                    </div>
                </div>
            }


        </div>

    </div>
</div>


@section Scripts
{

    <script type="text/javascript">

        function SoloLetras(e, controlId) {
            var caracter = e.key;
            if (!/^[a-zA-Z\u00C0-\u00FF ]*$/g.test(caracter)) {
                $('#' + controlId).text("Solo se aceptan letras");
                $('#' + controlId).css({ "color": "red" });
                return false;
            }
            else {
                $('#' + controlId).text("");
                return true;
            }
        }


    </script>
}

PL_MVC/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Materias</h2>
        </div>
    </div>

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success" })
        </div>

    </div>

    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id Materia</th>
                    <th>Nombre</th>
                    <th>Costo</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Materia materia in Model.Materias)
                {
                    <tr>
                        <td>@materia.IdMateria</td>
                        <td>@materia.Nombre</td>
                        <td>@materia.Costo</td>
                        
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Materia", new {IdMateria = materia.IdMateria})"></a></td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Materia", new {IdMateria = materia.IdMateria})" onclick=" return confirm('Estas seguro que quieres eliminar el resgitro=');"></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

</div>

PL_MVC/Views/Materia/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>